language: python
python: "2.7"
install: "basedir=$(pwd) ; for f in ${basedir}/lib/setups/*/setup.py ; do cd $(dirname $f) ; python $(basename $f) install &> /dev/null || if [[ $? -ne 0 ]] ; then echo \"Failed to install $f\" && exit -1 ; fi ; done ; cd $basedir"
script: "./run_tests.sh"
